### ISSUE TITLE
Проверка процессов регистрации, входа и восстановления пароля

### ISSUE THREAD

**Issue by the-teacher** [LaMaladieDespoir/ruby-test-job#5]
Прежде чем двигаться дальше, следует проверить функциональность базовых функций.

Следует проверить как ведет себя система в след. кейсах

1) Регистрация
2) Подтверждение учетной записи через почту и переход в личный кабинет
3) Повторный запрос на получения подтверждения регистрации
4) Выход из системы
5) Восстановление/смена пароля

этот функционал нужно откатать по полной. Оставлять его без внимания никак нельзя. Т.к. это и есть ядро системы.

Жду результатов тестирования и вопросов.

**Comment by LaMaladieDespoir** [comment]
Да, спасибо, помогло. Разобрался, самое обидное что ссзб, так как эти хелперы поменял я, когда обрабатывал вьюхи, типа у меня нет таких роутов, поэтому пропишем правильные. И вот проверить это не догадался. В ближайщее время завершу проверку функционала до конца.

**Comment by the-teacher** [comment]
:+1:

**Comment by LaMaladieDespoir** [comment]
Проверено:

1. Регистрация пользователя
2. Подтвержение по емейлу
3. Повторное получение инструкций о подтвержении
4. Восстановление пароля по емейлу
5. Смена пароля в личном кабинете

Промежуточные итоги задачи - функционал обкатан, вьюхи поправлены, перевод реализован. Пока вызывают неудовольствие - сообщения об ошибках (если не правильно набран пароль и так далее) и письмо на почту.

**Comment by the-teacher** [comment]
1) Для вывода ошибок предполагаю использовать отдельное решение. Это чуть позже. пока на это можно закрыть глаза.
2) Вид письма доработаем так же чуть позже. Главное, что бы ссылки в нем работали.

ок. идем дальше.

**Comment by the-teacher** [comment]
мое решение, позволяющее заменить стандартные рельсовые уведомления на чуть более приличные.

https://github.com/TheProfitCMS/the_notification
