### ISSUE TITLE
Подключение социальных сервисов

### ISSUE THREAD

**Issue by the-teacher** [LaMaladieDespoir/ruby-test-job#6]
Напомню. Наша задача - создать основу Rails приложения, которая позволит регистрировать пользователей различными способами. Этот фрагмент системы станет базовым для создания других проектов.

Следовательно нам нужно

1) Подключить к Devise основные плагины Omni-auth `twitter` `facebook` `vkontakte` `google`
2) Пройтись по всем указанным сетям, и для фейковых учеток (или любых доступных) получить API ключи. 
3) Создать текстовый файл, в котором сохранить пути к страницам получения OAuth API ключей, и кратко описать действия по получению данных ключей, что бы будущему пользователю нашего решения не пришлось искать эту информацию с нуля.
4) Подключить к Devise плагины и инициализировать их OAuth API ключами

**Comment by LaMaladieDespoir** [comment]
Сделано, описал действия получения ключей.

**Comment by the-teacher** [comment]
Принимаю код как работающий черновик. Держим в уме, что потребуется рефкторинг.

Перед постановкой новой задачи мне интересно получить твое личное мнение о фрагментах текущего кода и тех местах, которые на твой взгляд требуют переработки.

Зафиксируй, что нравится, а что не нравится. Что хотелось бы изменить и доработать.

Следующая задача последует сразу после этого.

**Comment by LaMaladieDespoir** [comment]
Что не нравится:
1. Не до конца локализовано приложение.
2. Много повторяющегося кода во вьюхах.
3. Сообщения об ошибках.
4. Отсутствия тестов.
5. Есть сомнительный код.

Что нравится:
1. Простой дизайн.
2. Что таки работает авторизация через соц.сети.
