### ISSUE TITLE
Подготовить данные для тестирования регистрации через соц сети

### ISSUE THREAD

**Issue by the-teacher** [LaMaladieDespoir/ruby-test-job#7]
Каждая соц сеть, при завершении авторизации веозвращает массив данных о пользователе который выполнил вход

эти данные представляют из себя JSON структуру

0. получить от каждой соц сети такой массив
0. сохратить массив в отдельный текстовый файл
0. отформатировать, что бы были видны уровни вложенности
0. заменить конфеденциальные данные на фэйки (менять только явно  секретные токены и ID, заменить их на что-то другое, но максимально похожее)

в резльтате ожидаю 4 текстовых файла с JSON структурой под каждую соц сеть

эти данные мы будем использовать для тестирования регистрации через соц сети, без необходимости обращаться непосредственно к самой соц сети.

**Comment by LaMaladieDespoir** [comment]
Сделано

**Comment by the-teacher** [comment]
1) не увидел ни новой ветки, ни прикрепленного кода для задачи
2) то что ты сохранил - это не JSON

**Comment by LaMaladieDespoir** [comment]
Почти сразу нашел конструкцию в env['omniauth.auth'] raw_info, но это был уже руби объект, и поэтому решил все же добраться до самого запроса. Для этого залез в гем, и в функции которая получает ответ от сервера вставил binding.pry чтобы убедиться что в raw_info лежит то, что нам нужно. Убрал отладку, вытащил из env['omniauth.auth'] raw_info в json формате.

**Comment by the-teacher** [comment]
не понимаю что происходит

это уже ближе, но тут нет тех данных которые мне нужны

всякий хеш данных должен содержать

поля первого уровня

0. provider
0. uid
0. info
0. credentials
0. extra

Ты их специально вырезал? если да, то верни. Без них процесс продолжить не можем т.к. ради них все и затеяно

**Comment by LaMaladieDespoir** [comment]
Сейчас верну.

**Comment by LaMaladieDespoir** [comment]
Сделал весь набор данных.

**Comment by the-teacher** [comment]
а данные вынул из объекта env['omniauth.auth'] ? без магии?

> без магии, только to_json
> чтобы в формат перевести
> ну я был не уверен что это что то нужно
