### ISSUE TITLE
Изучить как запускаются тесты

### ISSUE THREAD

**Issue by the-teacher** [LaMaladieDespoir/ruby-test-job#8]
0. Сейчас в проекте запускаются минитест тесты. Мне интересно, что бы ты попытался запустить их. Даже не смотря на то, что там нет ни одного. Важен сам факт запуска.
Сообщи о доп. действиях, которые потребовалось совершить для запуска. Смеха ради можешь написать один тест которые проверяет что `1 == 1`
0. мне важно, что бы ты понял что находится в файле `test_helper.rb` в первых 2х строках. Пожалуйста посмотри и напиши словами свое понимание того там написано.

**Comment by LaMaladieDespoir** [comment]
1. Перед выполнением тестов был сделан сброс базы данных командой rake db:drop:all

**Comment by LaMaladieDespoir** [comment]
2.  Файл ```test_helper.rb```
```
➜  ruby-test-job git:(issue_8) head test/test_helper.rb -n2
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
```
```ENV['RAILS_ENV'] ||= 'test'```
Насколько я понимаю, если переменная ```ENV['RAILS_ENV']``` - не объявлена или не имеет значения, то объявить переменную и установить значение равное ```'test'```, если переменная имеет значение то ничего не происходит.

```require File.expand_path('../../config/environment', __FILE__)```
Подключается файл ```environment``` с абсолютным путем, который возвращает функция ```File.expand_path``` в моем случае результат ```"/home/lmd/projects/ruby-test-job/config/enviroment"```
```__FILE__```- это имя файла, который сейчас активен. т.е.  ```'test_helper.rb'```

**Comment by the-teacher** [comment]
Прекрасно.

Смотри, из этого сделует, что ты можешь из любого скрипта сделать тест. Или даже сделать руби скрипт, который легко и просто будет работать с твоим рельсовым приложением.

Все что добавляют штуки вроде `mini_test` или `rspec` - это удобные хелперы для проверки ожиданий и реакция на падение кода.

А вообще тесты можно писать на коленке просто подключив рельсовое приложение в руби скрипт. Я называют такие тесты `плоскими` `plain`.  (это чисто моя терминология)
